/* This is a temporary helper that reads the tempscreen.pixdata file. tempscreen.pixdata is a 160x144 24-bit bmp file
 * with its header removed leaving only the pixel data. The pixel data is in rgb format (ie 3 bytes per pixel) but
 * since all pixels in the tempscreen file are in grey (r, g and b have the same value) scale and all pixels that
 * will be generated by the emulator will be in grey scale we only need to store the r-component in a texture (one
 * byte per pixel). The shaders will do the rest of the work.
 */

#include "temp_screen_helper.h"

namespace temporary{
    uint8_t* importTempscreen() {
        int texSize = BYTE_AMOUNT_FILE / 3;
        char* buffer = new char[BYTE_AMOUNT_FILE]; // tempscreen is in rgb format
        uint8_t* byteArr = new uint8_t[texSize]; // texture is in r format

        std::ifstream file("tempscreen.pixdata", ios::in | ios::binary);
        if (file.is_open()) {
            file.read(buffer, BYTE_AMOUNT_FILE);
            file.close();
        }
        else {
            return nullptr;
        }

        for (int i = 0; i < texSize; i += 1) {
            byteArr[i] = buffer[i * 3];
        }

        delete[] buffer;

        return byteArr;
    }
}